<?php

namespace DWD\TestAsimovBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * datesWithDeathRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class datesWithDeathRepository extends EntityRepository
{
}
